services:
  indexer:
    image: indexer:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://indexer:indexer@postgres:5432/eth_indexer
      ERC20_CONTRACT_ADDRESS: 0x1c7d4b196cb0c7b01d743fbc6116a902379c7238
      SEPOLIA_RPC_URL: ${INDEXER_RPC_URL}
      START_BLOCK_NUMBER: 7738800

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: indexer
      POSTGRES_USER: indexer
      POSTGRES_DB: eth_indexer
      PGDATA: /data
    entrypoint: docker-entrypoint.sh postgres -c log_statement=all
    volumes:
      - db-data:/data


volumes:
  db-data: